export const projects = [
  {
    title: 'Pizza Hunt',
    description: "This is an application that allows users to create their favourite pizza toppings, comment on other pizzas, and reply to comments. This is a PWA and uses MongoDB.",
    image: '/images/pizza-hunt.png',
    tags: ['JavaScript', 'Node.js', 'Express.js', 'MongoDB'],
    source: 'https://github.com/flovelace/pizza-hunt',
    visit: 'https://young-caverns-80211.herokuapp.com/',
    id: 0,
  },
  {
    title: 'Cool Tech Blog',
    description: "A tech blog that allows users to sign-up, login and logout with BCrypt. Users can write blog posts, and comment on other blog posts!",
    image: '/images/cool-tech-blog.png',
    tags: ['JavaScript', 'mySQL2', 'Bcrypt', 'Express.js'],
    source: 'https://github.com/flovelace/cool-tech-blog/',
    visit: 'https://sheltered-everglades-10281.herokuapp.com/',
    id: 1,
  },
  {
    title: 'Taskmaster Pro',
    description: "A kanban board that allows users to create tasks with a date picker modal. Users can drag and drop tasks in the columns for organisation.",
    image: '/images/taskmaster-pro.png',
    tags: ['JavaScript', 'jQuery', 'HTML5', 'CSS3'],
    source: 'https://github.com/flovelace/taskmaster-pro/',
    visit: 'https://flovelace.github.io/taskmaster-pro/',
    id: 2,
  },
  {
    title: 'Photography Portfolio',
    description: "A simple and clean portfolio for photographers built using React. It features conditionally rendered components such as modals and a contact form.",
    image: '/images/photo-portfolio.png',
    tags: ['JavaScript', 'React', 'CSS'],
    source: 'https://github.com/flovelace/photo-port',
    visit: 'photo-portfolio-fairfax.herokuapp.com/',
    id: 3,
  },
  {
    title: 'Note Taker',
    description: "A simple note taking app for hard workers on the go! This uses API to connect the front and back to save the user's notes.",
    image: '/images/note-taker.png',
    tags: ['JavaScript', 'REST API'],
    source: 'https://github.com/flovelace/note-taker/',
    visit: 'https://peaceful-castle-75538.herokuapp.com/',
    id: 4,
  },
];

export const TimeLineData = [
  { year: 2009, text: 'Achieved a BA Hons. (First Class) in English Studies.', },
  { year: 2010, text: 'Achieved a MLitt in the Gothic Imagination.', },
  { year: 2016, text: 'Immigrated to Toronto, ON, Canada.', },
  { year: 2019, text: 'Had an amazing time working in the FinTech industry with Naborly.', },
  { year: 2021, text: 'Began studying Full Stack Web Development at University of Toronto: School of Continuing Studies.', },
  { year: 2022, text: 'Completed Full Stack Web Development. Programming is life!', },
];